# Generated by Django 3.0.6 on 2022-09-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='session_end_year',
            new_name='session_end',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='session_start_year',
            new_name='session_start',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
    ]
