# Generated by Django 3.0.6 on 2022-09-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20220912_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
