# Generated by Django 3.0.6 on 2022-09-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20220921_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
