# Generated by Django 3.0.6 on 2022-08-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20220809_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
    ]
