# Generated by Django 3.0.6 on 2022-09-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20220927_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
