# Generated by Django 3.0.6 on 2022-09-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_delete_payments'),
        ('student_management_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
